apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: service-one
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: service-one
 minReplicas: 1
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
